substitutions:
  _REGION: 'us-central1'
  _DB_INSTANCE: 'mllm-sandbox-db-instance'
  _DB_NAME: 'mllm_sandbox_db'
  _DB_USER: 'mllm_sandbox_user'
  _VPC_CONNECTOR: 'mllm-vpc-connector'
  _GCS_BUCKET: 'prompting-sandbox-mvp-multiprompt-uploads'

steps:
  # Run backend tests
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y curl
        curl -LsSf https://astral.sh/uv/install.sh | sh
        export PATH="/builder/home/.local/bin:$$PATH"
        cd backend
        uv pip install --system -r requirements.txt
        uv pip install --system -r requirements-dev.txt
        python -m pytest tests/ -v --tb=short
    id: 'test-backend'
    env:
      - 'SECRET_KEY=a-secret-key-for-testing'

  # Get Cloud SQL private IP
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud sql instances describe ${_DB_INSTANCE} \
          --format='value(ipAddresses[0].ipAddress)' \
          --project=$PROJECT_ID > /workspace/db_host.txt
        echo "DB_HOST: $(cat /workspace/db_host.txt)"
    id: 'get-db-host'

  # Run database migrations
  # DISABLED: Database has private IP only, Cloud Build has no VPC access
  # Migrations run automatically on Cloud Run backend startup (see backend/Dockerfile CMD)
  # - name: 'python:3.11-slim'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       # Install curl and gcloud CLI
  #       apt-get update && apt-get install -y curl apt-transport-https ca-certificates gnupg
  #       curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
  #       echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  #       apt-get update && apt-get install -y google-cloud-cli
  #
  #       # Install cloud-sql-proxy
  #       curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64
  #       chmod +x cloud-sql-proxy
  #
  #       # Get DB password from Secret Manager
  #       DB_PASSWORD=$$(gcloud secrets versions access latest --secret=mllm_sandbox_user-password --project=$PROJECT_ID)
  #
  #       # Start proxy in background
  #       ./cloud-sql-proxy --port 5432 $PROJECT_ID:${_REGION}:${_DB_INSTANCE} &
  #       PROXY_PID=$$!
  #       sleep 5
  #
  #       # Install uv and dependencies
  #       curl -LsSf https://astral.sh/uv/install.sh | sh
  #       export PATH="/builder/home/.local/bin:$$PATH"
  #
  #       cd backend
  #       uv pip install --system -q -r requirements.txt
  #
  #       export DATABASE_URL="postgresql://${_DB_USER}:$${DB_PASSWORD}@localhost:5432/${_DB_NAME}"
  #       export SECRET_KEY="migration-temp-key"
  #       alembic upgrade head
  #
  #       # Cleanup
  #       kill $$PROXY_PID || true
  #   waitFor: ['get-db-host', 'test-backend']
  #   id: 'run-migrations'

  # Get existing Cloud Run URLs (for services that already exist)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get backend URL (may not exist on first deploy)
        BACKEND_URL=$$(gcloud run services describe multiprompt-backend \
          --region=${_REGION} --format='value(status.url)' \
          --project=$PROJECT_ID 2>/dev/null || echo "")

        # Get frontend URL (may not exist on first deploy)
        FRONTEND_URL=$$(gcloud run services describe multiprompt-frontend \
          --region=${_REGION} --format='value(status.url)' \
          --project=$PROJECT_ID 2>/dev/null || echo "")

        echo "$$BACKEND_URL" > /workspace/backend_url.txt
        echo "$$FRONTEND_URL" > /workspace/frontend_url.txt

        echo "Backend URL: $$BACKEND_URL"
        echo "Frontend URL: $$FRONTEND_URL"
    id: 'get-urls'
    waitFor: ['-']

  # Build backend image (parallel: starts after tests pass)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend']
    waitFor: ['-']
    id: 'build-backend'

  # Build frontend image (parallel: starts immediately, independent of backend tests)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA', '-f', 'frontend/Dockerfile', 'frontend']
    waitFor: ['-']  # Run immediately in parallel
    id: 'build-frontend'

  # Push backend image (runs after backend build)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA']
    waitFor: ['build-backend']
    id: 'push-backend'

  # Push frontend image (runs after frontend build, parallel to backend push)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA']
    waitFor: ['build-frontend']
    id: 'push-frontend'

  # Deploy backend to Cloud Run (parallel: runs after backend push + metadata ready)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_HOST=$$(cat /workspace/db_host.txt | tr -d '\n\r')
        FRONTEND_URL=$$(cat /workspace/frontend_url.txt | tr -d '\n\r')
        BACKEND_URL=$$(cat /workspace/backend_url.txt | tr -d '\n\r')

        # Use placeholder if URLs don't exist yet (first deploy)
        if [ -z "$$FRONTEND_URL" ]; then
          FRONTEND_URL="https://multiprompt-frontend-PLACEHOLDER.a.run.app"
        fi
        if [ -z "$$BACKEND_URL" ]; then
          BACKEND_URL="https://multiprompt-backend-PLACEHOLDER.a.run.app"
        fi

        # Cloud Run services have two URL formats - allow both for CORS
        PROJECT_NUMBER=$$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)' | tr -d '\n\r')
        FRONTEND_URL_ALT="https://multiprompt-frontend-$${PROJECT_NUMBER}.${_REGION}.run.app"
        CORS_VALUE="$${FRONTEND_URL},$${FRONTEND_URL_ALT}"

        echo "--- DEBUG: deploy-backend env vars ---"
        echo "DB_HOST: '$$DB_HOST'"
        echo "FRONTEND_URL: '$$FRONTEND_URL'"
        echo "BACKEND_URL: '$$BACKEND_URL'"
        echo "PROJECT_NUMBER: '$$PROJECT_NUMBER'"
        echo "FRONTEND_URL_ALT: '$$FRONTEND_URL_ALT'"
        echo "CORS_VALUE (for initial deploy): '$$CORS_VALUE'"

        # Create a temporary YAML file for initial deployment environment variables
        echo 'ENVIRONMENT: "production"' > deploy_env_vars.yaml
        echo "DB_HOST: \"$$DB_HOST\"" >> deploy_env_vars.yaml
        echo "DB_PORT: \"5432\"" >> deploy_env_vars.yaml
        echo "DB_USER: \"${_DB_USER}\"" >> deploy_env_vars.yaml
        echo "DB_NAME: \"${_DB_NAME}\"" >> deploy_env_vars.yaml
        echo "GCP_PROJECT_ID: \"$PROJECT_ID\"" >> deploy_env_vars.yaml
        echo "FRONTEND_URL: \"$$FRONTEND_URL\"" >> deploy_env_vars.yaml
        echo "GOOGLE_REDIRECT_URI: \"$$BACKEND_URL/api/v1/auth/google/callback\"" >> deploy_env_vars.yaml
        echo "CORS_ALLOWED_ORIGINS: \"$$CORS_VALUE\"" >> deploy_env_vars.yaml
        echo "GCS_BUCKET_NAME: \"${_GCS_BUCKET}\"" >> deploy_env_vars.yaml
        echo "--- DEBUG: deploy_env_vars.yaml content ---"
        cat deploy_env_vars.yaml
        echo "--- END DEBUG ---"

        gcloud run deploy multiprompt-backend \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --service-account=multiprompt-backend-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --vpc-connector=${_VPC_CONNECTOR} \
          --vpc-egress=private-ranges-only \
          --env-vars-file=deploy_env_vars.yaml \
          --set-secrets=DB_PASSWORD=mllm_sandbox_user-password:latest \
          --set-secrets=SECRET_KEY=multiprompt-secret-key:latest \
          --set-secrets=GOOGLE_CLIENT_ID=google-client-id:latest \
          --set-secrets=GOOGLE_CLIENT_SECRET=google-client-secret:latest \
          --set-secrets=GEMINI_API_KEY=multiprompt-gemini-api-key:latest \
          --set-secrets=ADMIN_EMAILS=multiprompt-admin-emails:latest \
          --set-secrets=ALLOWED_EMAIL_DOMAINS=multiprompt-allowed-domain:latest \
          --memory=2Gi \
          --cpu=2 \
          --timeout=600 \
          --min-instances=0 \
          --max-instances=10
    waitFor: ['push-backend', 'get-db-host', 'get-urls']
    id: 'deploy-backend'

  # Deploy frontend to Cloud Run (parallel: runs after frontend push)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'multiprompt-frontend'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
    waitFor: ['push-frontend']
    id: 'deploy-frontend'

  # Update backend with actual URLs after both services are deployed
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$$(gcloud run services describe multiprompt-backend \
          --region=${_REGION} --format='value(status.url)' --project=$PROJECT_ID | tr -d '\n\r')
        FRONTEND_URL=$$(gcloud run services describe multiprompt-frontend \
          --region=${_REGION} --format='value(status.url)' --project=$PROJECT_ID | tr -d '\n\r')

        # Cloud Run services have two URL formats - allow both for CORS
        PROJECT_NUMBER=$$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)' | tr -d '\n\r')
        FRONTEND_URL_ALT="https://multiprompt-frontend-$${PROJECT_NUMBER}.${_REGION}.run.app"
        CORS_VALUE="$${FRONTEND_URL},$${FRONTEND_URL_ALT}"

        echo "--- DEBUG: update-urls step ---"
        echo "Raw FRONTEND_URL: '$${FRONTEND_URL}'"
        echo "Raw BACKEND_URL: '$${BACKEND_URL}'"
        echo "Raw PROJECT_NUMBER: '$${PROJECT_NUMBER}'"
        echo "Constructed FRONTEND_URL_ALT: '$${FRONTEND_URL_ALT}'"
        echo "Final CORS_VALUE: '$${CORS_VALUE}'"

        # Use multiple --update-env-vars flags to avoid delimiter issues with URLs
        gcloud run services update multiprompt-backend \
          --region=${_REGION} \
          --update-env-vars FRONTEND_URL=$${FRONTEND_URL} \
          --update-env-vars GOOGLE_REDIRECT_URI=$${BACKEND_URL}/api/v1/auth/google/callback \
          --update-env-vars CORS_ALLOWED_ORIGINS=$${CORS_VALUE}

    waitFor: ['deploy-backend', 'deploy-frontend']
    id: 'update-urls'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
