steps:
  # Run backend tests
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        pip install -r requirements.txt
        python -m pytest tests/ -v --tb=short
    id: 'test-backend'

  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend']
    waitFor: ['test-backend']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'multiprompt-backend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--vpc-connector=mllm-vpc-connector'
      - '--vpc-egress=private-ranges-only'
      - '--set-env-vars=ENVIRONMENT=production,DB_HOST=10.205.0.3,DB_PORT=5432,DB_USER=mllm_sandbox_user,DB_NAME=mllm_sandbox_db,GCP_PROJECT_ID=$PROJECT_ID,FRONTEND_URL=https://multiprompt-frontend-h7qqra6pma-uc.a.run.app,GOOGLE_REDIRECT_URI=https://multiprompt-backend-h7qqra6pma-uc.a.run.app/api/v1/auth/google/callback'
      - '--set-secrets=DB_PASSWORD=mllm_sandbox_user-password:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA', '-f', 'frontend/Dockerfile', 'frontend']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'multiprompt-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
