substitutions:
  _REGION: 'us-central1'
  _DB_INSTANCE: 'multiprompt-db'
  _DB_NAME: 'multiprompt'
  _DB_USER: 'multiprompt'
  _VPC_CONNECTOR: 'mllm-vpc-connector'

steps:
  # Run backend tests
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        pip install -r requirements.txt
        python -m pytest tests/ -v --tb=short
    id: 'test-backend'

  # Get Cloud SQL private IP
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud sql instances describe ${_DB_INSTANCE} \
          --format='value(ipAddresses[0].ipAddress)' \
          --project=$PROJECT_ID > /workspace/db_host.txt
        echo "DB_HOST: $(cat /workspace/db_host.txt)"
    id: 'get-db-host'

  # Get existing Cloud Run URLs (for services that already exist)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get backend URL (may not exist on first deploy)
        BACKEND_URL=$$(gcloud run services describe multiprompt-backend \
          --region=${_REGION} --format='value(status.url)' \
          --project=$PROJECT_ID 2>/dev/null || echo "")

        # Get frontend URL (may not exist on first deploy)
        FRONTEND_URL=$$(gcloud run services describe multiprompt-frontend \
          --region=${_REGION} --format='value(status.url)' \
          --project=$PROJECT_ID 2>/dev/null || echo "")

        echo "$$BACKEND_URL" > /workspace/backend_url.txt
        echo "$$FRONTEND_URL" > /workspace/frontend_url.txt

        echo "Backend URL: $$BACKEND_URL"
        echo "Frontend URL: $$FRONTEND_URL"
    id: 'get-urls'
    waitFor: ['-']

  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA', '-f', 'backend/Dockerfile', 'backend']
    waitFor: ['test-backend']
    id: 'build-backend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA']
    id: 'push-backend'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_HOST=$$(cat /workspace/db_host.txt)
        FRONTEND_URL=$$(cat /workspace/frontend_url.txt)
        BACKEND_URL=$$(cat /workspace/backend_url.txt)

        # Use placeholder if URLs don't exist yet (first deploy)
        if [ -z "$$FRONTEND_URL" ]; then
          FRONTEND_URL="https://multiprompt-frontend-PLACEHOLDER.a.run.app"
        fi
        if [ -z "$$BACKEND_URL" ]; then
          BACKEND_URL="https://multiprompt-backend-PLACEHOLDER.a.run.app"
        fi

        gcloud run deploy multiprompt-backend \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --vpc-connector=${_VPC_CONNECTOR} \
          --vpc-egress=private-ranges-only \
          --set-env-vars="ENVIRONMENT=production,DB_HOST=$$DB_HOST,DB_PORT=5432,DB_USER=${_DB_USER},DB_NAME=${_DB_NAME},GCP_PROJECT_ID=$PROJECT_ID,FRONTEND_URL=$$FRONTEND_URL,GOOGLE_REDIRECT_URI=$$BACKEND_URL/api/v1/auth/google/callback,CORS_ALLOWED_ORIGINS=$$FRONTEND_URL" \
          --set-secrets=DB_PASSWORD=multiprompt-db-password:latest,SECRET_KEY=multiprompt-secret-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GEMINI_API_KEY=multiprompt-gemini-api-key:latest \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10
    waitFor: ['get-db-host', 'get-urls', 'push-backend']
    id: 'deploy-backend'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA', '-f', 'frontend/Dockerfile', 'frontend']
    id: 'build-frontend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA']
    id: 'push-frontend'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'multiprompt-frontend'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
    waitFor: ['push-frontend']
    id: 'deploy-frontend'

  # Update backend with actual URLs after both services are deployed
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get actual URLs after deployment
        BACKEND_URL=$$(gcloud run services describe multiprompt-backend \
          --region=${_REGION} --format='value(status.url)' --project=$PROJECT_ID)
        FRONTEND_URL=$$(gcloud run services describe multiprompt-frontend \
          --region=${_REGION} --format='value(status.url)' --project=$PROJECT_ID)

        echo "Updating backend with final URLs..."
        echo "Backend: $$BACKEND_URL"
        echo "Frontend: $$FRONTEND_URL"

        gcloud run services update multiprompt-backend \
          --region=${_REGION} \
          --update-env-vars="FRONTEND_URL=$$FRONTEND_URL,GOOGLE_REDIRECT_URI=$$BACKEND_URL/api/v1/auth/google/callback,CORS_ALLOWED_ORIGINS=$$FRONTEND_URL"
    waitFor: ['deploy-backend', 'deploy-frontend']
    id: 'update-urls'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/backend:$COMMIT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/multiprompt/frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
