"""add_cost_tracking_columns

Revision ID: 4817bfb92f7f
Revises: add_selection_config
Create Date: 2025-12-09 22:49:09.946231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4817bfb92f7f'
down_revision: Union[str, None] = 'add_selection_config'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('actual_cost', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('cost_details', sa.JSON(), nullable=True))
    op.add_column('model_configs', sa.Column('pricing_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_configs', 'pricing_config')
    op.drop_column('evaluations', 'cost_details')
    op.drop_column('evaluations', 'actual_cost')
    op.drop_column('evaluations', 'estimated_cost')
    # ### end Alembic commands ###
