"""add_thumbnail_data_to_images

Revision ID: 546b11d4efbc
Revises: 547765d3dbe9
Create Date: 2025-11-26 15:41:21.083810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546b11d4efbc'
down_revision: Union[str, None] = '547765d3dbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('thumbnail_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'thumbnail_data')
    # ### end Alembic commands ###
