"""add system message and question text to evaluations

Revision ID: 547765d3dbe9
Revises: f9a2c1b8d3e5
Create Date: 2025-11-26 00:27:48.774668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547765d3dbe9'
down_revision: Union[str, None] = 'f9a2c1b8d3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('system_message', sa.Text(), nullable=True))
    op.add_column('evaluations', sa.Column('question_text', sa.Text(), nullable=True))
    op.alter_column('model_configs', 'concurrency',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_configs', 'concurrency',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.drop_column('evaluations', 'question_text')
    op.drop_column('evaluations', 'system_message')
    # ### end Alembic commands ###
