"""add_processing_status_columns

Revision ID: 640889d5a1e8
Revises: 546b11d4efbc
Create Date: 2025-11-27 23:58:00.893957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640889d5a1e8'
down_revision: Union[str, None] = '546b11d4efbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults for existing rows
    op.add_column('datasets', sa.Column('processing_status', sa.String(), nullable=False, server_default='ready'))
    op.add_column('datasets', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('datasets', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('datasets', sa.Column('total_files', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('datasets', sa.Column('processed_files', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('datasets', sa.Column('failed_files', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('datasets', sa.Column('processing_errors', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('processing_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('images', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'processing_error')
    op.drop_column('images', 'processing_status')
    op.drop_column('datasets', 'processing_errors')
    op.drop_column('datasets', 'failed_files')
    op.drop_column('datasets', 'processed_files')
    op.drop_column('datasets', 'total_files')
    op.drop_column('datasets', 'processing_completed_at')
    op.drop_column('datasets', 'processing_started_at')
    op.drop_column('datasets', 'processing_status')
    # ### end Alembic commands ###
