"""add_split_columns_to_labelling_jobs

Revision ID: 8b1234567890
Revises: 7a92c3d8f1b5
Create Date: 2024-05-23 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b1234567890'
down_revision: Union[str, None] = '7a92c3d8f1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labelling_jobs', sa.Column('target_split_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('labelling_jobs', sa.Column('exclude_split_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'labelling_jobs', 'dataset_splits', ['target_split_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'labelling_jobs', 'dataset_splits', ['exclude_split_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labelling_jobs', type_='foreignkey')
    op.drop_constraint(None, 'labelling_jobs', type_='foreignkey')
    op.drop_column('labelling_jobs', 'exclude_split_id')
    op.drop_column('labelling_jobs', 'target_split_id')
    # ### end Alembic commands ###
