"""create_annotation_import_jobs_table

Revision ID: bdb80060ab5f
Revises: 36f3dd453206
Create Date: 2025-12-21 19:14:47.514214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb80060ab5f'
down_revision: Union[str, None] = '36f3dd453206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_datasets_created_by_id'), table_name='datasets')
    op.drop_index(op.f('idx_datasets_project_id'), table_name='datasets')
    op.drop_index(op.f('idx_evaluation_results_evaluation_id'), table_name='evaluation_results')
    op.drop_index(op.f('idx_evaluation_results_evaluation_id_is_correct'), table_name='evaluation_results')
    op.drop_index(op.f('idx_evaluations_created_by_id_created_at'), table_name='evaluations')
    op.drop_index(op.f('idx_evaluations_project_id'), table_name='evaluations')
    op.drop_index(op.f('idx_images_dataset_id_filename'), table_name='images')
    op.drop_index(op.f('idx_images_dataset_id_uploaded_at'), table_name='images')
    op.drop_index(op.f('idx_images_dataset_processing_status'), table_name='images')
    op.drop_index(op.f('idx_projects_created_at'), table_name='projects')
    op.drop_index(op.f('idx_projects_created_by_id'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_projects_created_by_id'), 'projects', ['created_by_id'], unique=False)
    op.create_index(op.f('idx_projects_created_at'), 'projects', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_images_dataset_processing_status'), 'images', ['dataset_id', 'processing_status'], unique=False)
    op.create_index(op.f('idx_images_dataset_id_uploaded_at'), 'images', ['dataset_id', sa.literal_column('uploaded_at DESC')], unique=False)
    op.create_index(op.f('idx_images_dataset_id_filename'), 'images', ['dataset_id', 'filename'], unique=False)
    op.create_index(op.f('idx_evaluations_project_id'), 'evaluations', ['project_id'], unique=False)
    op.create_index(op.f('idx_evaluations_created_by_id_created_at'), 'evaluations', ['created_by_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_evaluation_results_evaluation_id_is_correct'), 'evaluation_results', ['evaluation_id', 'is_correct'], unique=False)
    op.create_index(op.f('idx_evaluation_results_evaluation_id'), 'evaluation_results', ['evaluation_id'], unique=False)
    op.create_index(op.f('idx_datasets_project_id'), 'datasets', ['project_id'], unique=False)
    op.create_index(op.f('idx_datasets_created_by_id'), 'datasets', ['created_by_id'], unique=False)
    # ### end Alembic commands ###
