"""create_annotation_import_jobs_table

Revision ID: bdb80060ab5f
Revises: 36f3dd453206
Create Date: 2025-12-21 19:14:47.514214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSON

# revision identifiers, used by Alembic.
revision: str = 'bdb80060ab5f'
down_revision: Union[str, None] = '36f3dd453206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'annotation_import_jobs',
        sa.Column('id', UUID(as_uuid=True), primary_key=True),
        sa.Column('dataset_id', UUID(as_uuid=True), sa.ForeignKey('datasets.id'), nullable=False),
        sa.Column('created_by_id', UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='importjobstatus'), nullable=False),
        sa.Column('temp_file_path', sa.String(), nullable=True),
        sa.Column('total_rows', sa.Integer(), default=0),
        sa.Column('processed_rows', sa.Integer(), default=0),
        sa.Column('created_count', sa.Integer(), default=0),
        sa.Column('updated_count', sa.Integer(), default=0),
        sa.Column('skipped_count', sa.Integer(), default=0),
        sa.Column('error_count', sa.Integer(), default=0),
        sa.Column('errors', JSON(), default=list),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation_import_jobs')
    # Manually drop the enum type if it was created
    sa.Enum(name='importjobstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###