"""add_multi_phase_prompting_support

Revision ID: fcfbf17e4102
Revises: 4e8b5c417f8f
Create Date: 2025-12-02 21:33:27.954952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfbf17e4102'
down_revision: Union[str, None] = '4e8b5c417f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('step_results', sa.JSON(), nullable=True))
    op.add_column('evaluations', sa.Column('prompt_chain', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'prompt_chain')
    op.drop_column('evaluation_results', 'step_results')
    # ### end Alembic commands ###
